version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
        - cinema
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile-client
    networks:
        - cinema
    depends_on:
        - server
networks:
    cinema:
